### ISSUE TITLE
PA Review -Profiles view

### ISSUE THREAD

**Issue by Meenakshi-Anand** [Meenakshi-Anand/Facebook-Clone#3]
- [x] Logged in users can view his profile picture and cover photos.
- [ ] Logged in user can view his posts.
- [ ] Adequate styling
- [ ] Smooth, bug-free navigation
- [ ] Seeded with info to demonstrate this feature

**Comment by eshoule** [comment]
Looks good. I'm not going to fully close this until a user is allowed to make posts or posts are seeded because I can't see any posts right now. But you should fix the below issue and move on to the other MVPs. 

- [x] When I signup, my profile page is not rendered until I click on my name in the nav bar. Make the page appear immediately.

**Comment by Meenakshi-Anand** [comment]
When the user signs up he is shown his news feed page , which is not implemented yet.

**Comment by eshoule** [comment]
Ok, sounds good. I will close this issue once the app is seeded with posts, and they show up on the profile. Good job!

**Comment by Meenakshi-Anand** [comment]
Fixed issued
